### ISSUE TITLE
"use previous analysis feature"

### ISSUE THREAD

**Issue by hollyallen8** [bdavis222/dotscanner#19]
This feature wouldn't work for me. It kept coming up with this error

Traceback (most recent call last):
  File "/opt/anaconda3/bin/dotscanner", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.8/site-packages/dotscanner/__main__.py", line 21, in main
    getDensityData(directory, filenames, userSettings)
  File "/opt/anaconda3/lib/python3.8/site-packages/dotscanner/__main__.py", line 41, in getDensityData
    microscopeImage = MicroscopeImage(directory, filename, userSettings)
  File "/opt/anaconda3/lib/python3.8/site-packages/dotscanner/ui/MicroscopeImage.py", line 9, in __init__
    self.polygon = self.getPolygon(filename, userSettings)
  File "/opt/anaconda3/lib/python3.8/site-packages/dotscanner/ui/MicroscopeImage.py", line 55, in getPolygon
    return userSettings.densityData[filename][7]
KeyError: 'SD 525-2.tif'

**Comment by hollyallen8** [comment]
/Users/holly/Library/Mobile Documents/com~apple~CloudDocs/PSU Work/Papers/Methods paper/Dual images from ying - RFPCSI1, GFPCSI3
